[common]
use_local = false
use_s3 = true
use_memo = true
use_ipfs = false
read_only = false
repo_dir = "/home/lighthouse/mpath"
max_upload_bytes = 1099511627776 # 1TiB
bucketname = "mefstest" # set bucketname the gateway to use
root_dir = "~/.mefs_gw"
local_dir = ""
console = ":8080"
endpoint = "0.0.0.0:5080"

[s3]
endpoint = "s3-qos.my-sz-1.qiniu-solutions.com:29091"
region = "z0"
accesskey = "22taR9gKak3fXfDYT-GqSjxGc_uslfiNC0ocxPK_"
secretkey = "VHr2Q1q3dRfZ7nXZPUnmRtlM0Wh_hDAWbzniSIlZ"
