[common]
use_local = true
use_s3 = false
max_upload_bytes = 1099511627776 # 1TiB
bucketname = "mefstest" # set bucketname the gateway to use
root_dir = "~/.mefs_gw"
local_dir = ""
read_only = true

[s3]
endpoint = "s3-qos.my-sz-1.qiniu-solutions.com:29091"
region = "z0"
accesskey = "22taR9gKak3fXfDYT-GqSjxGc_uslfiNC0ocxPK_"
secretkey = "VHr2Q1q3dRfZ7nXZPUnmRtlM0Wh_hDAWbzniSIlZ"
